config/routes.rb
VarnishdSkillshare::Application.routes.draw do
  root to: "application#home"
  match "/your_ip" => "application#your_ip"

  match "/static" => "application#static"

  namespace :private do
    resource :content
  end

  resource :feed do
    resources :feed_items, :path => "items"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :cache_me, only: [:home, :static]
  before_filter :do_esi, only: :home

  def home
    render
  end

  def your_ip
    render "_your_ip.html.erb", layout: false
  end

  def static
    render
  end

  private

  def cache_me
    response.headers['Cache-Control'] = "public"
    response.headers['Expires'] =  1.hour.from_now.httpdate
  end

  def do_esi
    response.headers['X-Esi-Processing'] = "on"
    # We do this so that varnish doesn't have to unzip
    # the content before ESI processing.
    request.env.delete( 'HTTP_X_ACCEPT_ENCODING' )
  end
end

app/controllers/feed_items_controller.rb
class FeedItemsController < ApplicationController
  def show

    respond_to do |format|
      format.html {
        if params[:id][0] == "X"
          cache_me
          do_esi
        else
          @item = $redis.hgetall( params[:id] )
        end
      }
      format.esi {
        @item = $redis.hgetall( params[:id] )
        cache_me
        render "_fragment.html.erb", layout: false
      }
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def show
    do_esi
    @items = $redis.lrange( "feed", 0, 10 )
  end
end

app/controllers/private/application_controller.rb
class Private::ApplicationController < ApplicationController

  before_filter :require_login

  private

  def require_login
    if params[:auth_token]
      if params[:auth_token] != "XXXXXX"
        # rejects requests with wrong token
        render text: "Auth secret invalid", status:  :forbidden
      end
      # otherwise, let page render and set caching headers
    else
      authenticate_or_request_with_http_basic do |username, password |
        if username == "username" && password == "password"
          if Rails.env.development? || request.env['HTTP_X_VARNISHD_SECRET'] == 'rPo7CkECQTW4Pu2UzdpbLk2Rs10mxGPf8W9CQ1k5z2nKXV/aTjls94vdHzlAWwxh'
            do_esi
            # Adds auth token XXXXXX to current url and esi includes it
            render text: "<esi:include xmlns:esi=\"http://www.edge-delivery.org/esi/1.0\" src=\"#{url_for( auth_token: "XXXXXX" )}\" onerror=\"continue\" />", content_type: "text/html"
          else
            render text: "Oh no you didn't!", status:  :forbidden
          end
        else
          head :unauthorized
        end
      end
    end
  end
end

app/controllers/private/contents_controller.rb
class Private::ContentsController < Private::ApplicationController
  def show
    cache_me
    render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_your_ip.html.erb
<p>
  <% smart_ips = (request.env['HTTP_X_FORWARDED_FOR'] || request.remote_ip).split( "," ) %>
  Your ip is <%= smart_ips.first %>   and your user agent is <%=  request.user_agent %><br/><br/>

  <% if Rails.env.production? %>
    <%  PinPoint.ip( smart_ips.first ).tap { |blk| next if blk.nil? ; %><strong>I think you're in <%=  blk.city %>, <%=  blk.state %></strong> <% } %><br/>
  <% end %>

  <br/>
  <br/>
  Timestamp: <%=  Time.now.to_s %>
</p>

app/views/application/home.html.erb
<div id="feed-body" class="container">
  <div class="row">
    <div class="span8">
      <div class="corgi_feed_well">
        <div class="feed_stacked">
          <div class="feed_item">
            <div class="feed_body">
              <div class="row">
                <div class="feed_profile_pic">
                  <%= image_tag "corgi.jpg", :class => "meta_image" %>
                </div>
                <div class="feed_text">
                    <%= render partial: 'your_ip' %>
                </div>
              </div>
            </div>
            <div class="comment_area">
              <p>Add a comment</p>
              <form>
                <textarea rows="3" class="span6"></textarea><br/>
                <input type="submit" class="btn" />
              </form>
            </div>
            <hr class="feed_hr">
            <div class="bottom_meta">
              <div class="row">
                <div class="bottom_left">
                  <div class="share_wrapper">
                    <div class="share"><a href="#" class="share_button"><i class="icon-heart"></i></a></div>
                    <div class="share_hidden">
                      <ul class="hover_heart">
                        <span class="internal_heart"><i class="icon-heart"></i> Share This Post</span>
                        <div class="social_links">
                          <li><span><i class="icon-twitter"></i> Twitter</span></li>
                          <li><span><i class="icon-facebook"></i> Facebook</span></li>
                          <li><span><i class="icon-pinterest"></i> Pinterest</span></li>
                        </div>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="bottom_right">
                  <a href="#">Corgi_like_bacon1</a> <span>|</span> <a href="#" class="show_comment_link">comment</a> <span>|</span> 2 days ago
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div> <!-- end span8 -->
    <div class="span4">
      <div class="corgi_feed_well">
        <div class="sidebar_header">
          <div class="sidebar_title">
            <h4>Explanatory Sidebar</h4>
          </div>
        </div>
        <hr class="feed_hr" />
        <div class="sidebar_interior">
          <i class="icon-ok"></i> IP is real!
          <br/><br/>
          <i class="icon-ok"></i> Geo location is dynamic!
          <br/><br/>
          <i class="icon-ok"></i> Amazing!
          <br/><br/>
          <i class="icon-hand-right"></i> Rendered at <%=  Time.now.utc.strftime( "%H:%M:%S" ) %> UTC
          <br/><br/>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/application/static.html.erb
<div id="feed-body" class="container">
  <div class="row">
    <div class="span8">
      <div class="corgi_feed_well">
        <div class="feed_stacked">
          <div class="feed_item">
            <div class="feed_body">
              <div class="row">
                <div class="feed_profile_pic">
                  <%= image_tag "corgi.jpg", :class => "meta_image" %>
                </div>
                <div class="feed_text">
                  <h2>This page just has a lot of static content</h2>
                  <p>Bacon ipsum dolor sit amet est ex ullamco, et ad sint voluptate t-bone. Aute boudin jowl
                    reprehenderit id ad. Meatball ut swine, turducken strip steak minim ea aute doner sausage pork loin.
                    Veniam et aute salami reprehenderit. Anim deserunt tenderloin meatball, frankfurter consequat
                    bresaola tempor.</p>

                  <p>Brisket bresaola est, sunt adipisicing qui turducken leberkas pancetta ham aute voluptate sint ham
                    hock. Laborum ut velit, elit consectetur anim pork chop shank incididunt qui non fugiat tail. Qui
                    beef ribs culpa ball tip leberkas do commodo sint eiusmod irure brisket. Labore pork jowl pig
                    eiusmod cupidatat tri-tip beef prosciutto pariatur nisi pancetta. Ground round beef ribs ham
                    fugiat.</p>

                  <p>Laboris magna shoulder do. Incididunt cupidatat flank in, ribeye turkey mollit consectetur brisket
                    jerky chicken pork belly sunt. Non boudin in spare ribs, ham hock prosciutto irure exercitation beef
                    ribs. Capicola tempor drumstick eiusmod shankle shoulder jerky prosciutto sint ball tip pork belly.
                    In ut short loin tempor.</p>

                  <p>Ball tip ham t-bone, doner turducken sint pastrami culpa. Qui venison shank chicken. Drumstick
                    jerky fatback mollit fugiat aute beef ribs nulla duis shank jowl sunt cow nostrud proident. Quis
                    esse ex ut spare ribs turducken labore incididunt fugiat laboris adipisicing et prosciutto. Ut
                    meatball est mollit eu. Minim meatloaf pork belly eiusmod turducken. Irure flank prosciutto, ullamco
                    dolore drumstick pariatur nostrud do short loin bresaola.</p>

                  <p>Esse shoulder ball tip, venison pariatur eu ut consectetur cillum leberkas culpa pork frankfurter
                    occaecat ham. Sed irure excepteur pork loin. Aliqua capicola pastrami ball tip dolor tail tongue
                    shankle occaecat in. Excepteur ut bacon, jerky et ham frankfurter id tri-tip in meatball chuck.</p>

                  <p>Est in adipisicing tri-tip. Pariatur velit non exercitation hamburger strip steak proident bacon do
                    incididunt occaecat aliquip officia ball tip. Quis veniam ad dolor cow short ribs ground round
                    andouille aute shank do spare ribs short loin proident. Mollit doner jowl, sunt frankfurter rump
                    elit flank fatback eiusmod. Aliquip id strip steak ball tip turkey.</p>

                  <p>Pariatur est rump short loin eiusmod in ullamco ut consectetur swine ut strip steak aute ham ad.
                    Pork ham hock esse ut, pig qui flank fatback sint. Corned beef ea culpa sunt quis spare ribs aliqua
                    ham hock nulla laboris proident chuck voluptate meatball ham. Voluptate nulla deserunt, ullamco jowl
                    aliqua shank kielbasa nostrud bresaola. Consequat turkey voluptate corned beef.</p>

                  <p>Eiusmod ut voluptate exercitation. Aliqua exercitation fugiat doner capicola, elit tail voluptate
                    pork loin sed ex. Magna esse pork shank tenderloin, cow eu exercitation tri-tip in meatball officia
                    capicola. Capicola andouille pancetta pork belly dolore occaecat ullamco ad culpa duis
                    incididunt.</p>

                  <p>Do shankle biltong venison jowl quis in boudin. Strip steak filet mignon ex, dolore corned beef
                    minim meatball salami et in pastrami turducken reprehenderit culpa. Pork chop duis et, sirloin dolor
                    swine adipisicing pig turkey tri-tip non ham hock in. Pariatur occaecat beef ribs, sed ut eiusmod
                    chicken prosciutto shankle nostrud drumstick swine andouille cow frankfurter. Aliquip turkey
                    pariatur, nisi beef meatball occaecat.</p>

                  <p>Biltong pork loin rump aliquip in andouille. Est spare ribs short loin id aute beef ribs pig
                    ullamco velit ham irure. Pork loin andouille fugiat doner incididunt short loin exercitation sunt
                    beef ribs irure swine tenderloin qui officia dolore. Shankle ex spare ribs cillum, t-bone sed
                    voluptate. Voluptate doner ut tail, pariatur aliquip ea nisi mollit et exercitation anim sint short
                    loin. Dolore officia occaecat, excepteur beef ribs id ut proident sausage mollit sirloin corned beef
                    swine turducken nostrud.</p>

                  <p>Enim t-bone jerky minim. Esse venison short loin, ut salami consectetur sed quis voluptate ex
                    nostrud chicken. Consectetur turducken duis jowl anim meatloaf bacon adipisicing, short ribs pork
                    chop filet mignon. Ham hock magna non kielbasa ullamco in nostrud. Rump tongue consequat duis bacon
                    strip steak. Bacon non aute voluptate, meatloaf incididunt strip steak. Est in enim aliquip t-bone
                    mollit.</p>

                  <p>Beef magna turkey tail ribeye ut occaecat prosciutto quis pork cupidatat rump aute laborum
                    incididunt. Chicken voluptate ex biltong et in ullamco tail tri-tip corned beef elit tenderloin
                    nostrud. T-bone jowl velit pastrami venison enim in consequat fatback. Officia swine chuck short
                    loin ribeye sausage shankle labore laboris, turducken ham. Dolor leberkas labore non, turducken
                    proident beef ribs irure ad spare ribs meatball et nisi eu cupidatat. Dolore filet mignon aute
                    drumstick enim nisi sint qui laborum aliquip bacon. Cillum tenderloin jowl, dolore filet mignon
                    bresaola fatback short ribs nostrud.</p>

                  <p>Officia ribeye bresaola flank hamburger. Jerky consectetur shank pastrami bacon. Beef ex non nisi,
                    filet mignon duis laboris ground round veniam sed capicola turducken. Pork chop andouille pork, ut
                    dolore fatback reprehenderit in veniam in. Duis shoulder doner shank shankle.</p>

                  <p>Fatback esse meatloaf turducken, aliquip ad duis ham hock. Labore officia magna ham hock sed pork
                    loin. Pork laborum beef ribs bresaola dolore id. Jowl pork belly consectetur et sint est bresaola.
                    Dolore aliquip meatloaf in anim qui corned beef sunt irure magna bacon short ribs nisi kielbasa
                    jerky. Ullamco flank et, chicken adipisicing tempor veniam qui salami meatloaf short loin
                    boudin.</p>

                  <p>Tempor leberkas adipisicing doner, venison swine hamburger turducken cupidatat dolor. Deserunt ham
                    hock venison pork chop, ut swine et occaecat officia esse sirloin aute. Ham turducken est sint
                    dolore ut. Kielbasa veniam ut occaecat.</p>

                  <p>Corned beef filet mignon ground round tenderloin, eiusmod boudin in pork loin adipisicing shoulder.
                    Cow t-bone enim chicken ut minim. Ullamco pork loin enim jerky do labore andouille ut cillum.
                    Biltong eiusmod frankfurter drumstick sunt sint deserunt corned beef.</p>

                  <p>Prosciutto shankle kielbasa ball tip aute qui. Esse sint officia qui, ut ham pig corned beef
                    pastrami brisket nisi minim elit meatloaf. Jowl short ribs nisi chuck irure adipisicing, corned beef
                    fugiat tongue pig aliquip ullamco beef ribs reprehenderit. Capicola non t-bone kielbasa culpa
                    laboris cillum. Boudin tri-tip esse officia id rump. Meatball fatback tri-tip kielbasa, id pork chop
                    quis consectetur cillum nostrud eiusmod ground round spare ribs strip steak andouille. Sed qui ham
                    hock swine, ex consequat duis hamburger enim shank sunt in.</p>

                  <p>Ball tip cow brisket irure corned beef ut dolore adipisicing ex chicken beef ribs flank ea short
                    ribs. Pork loin sed excepteur meatloaf sunt, minim sausage fugiat id dolore aliqua in pork chop.
                    Sirloin in fatback prosciutto shank reprehenderit. Turducken excepteur id nisi brisket commodo. Ut
                    elit aute consectetur capicola tri-tip, pastrami beef.</p>

                  <p>Frankfurter in occaecat, biltong cow elit shankle tri-tip id nostrud aliqua deserunt pork loin.
                    Magna ut et consequat. Pariatur sausage kielbasa sunt, culpa esse strip steak nulla pig do
                    consectetur non rump cupidatat hamburger. Ut prosciutto shankle duis commodo minim, pig chuck ex
                    exercitation dolore jerky bresaola tenderloin incididunt. Adipisicing short loin ribeye ball tip
                    aliqua incididunt doner tail filet mignon minim elit.</p>

                  <p>Drumstick shank occaecat, sed nulla est pancetta filet mignon minim. Corned beef est ball tip
                    ground round bresaola doner prosciutto. Duis pork belly incididunt nostrud turducken magna dolor
                    ground round enim in sunt biltong mollit ham hock dolore. Irure aliqua cupidatat rump in short loin
                    pig. Beef non sint, ex venison dolore jerky. Ribeye in veniam filet mignon, strip steak doner
                    incididunt frankfurter beef ribs. Ea flank do boudin shankle proident laborum nostrud.</p></div>
              </div>
            </div>
            <div class="comment_area">
              <p>Add a comment</p>
              <form>
                <textarea rows="3" class="span6"></textarea><br/>
                <input type="submit" class="btn" />
              </form>
            </div>
            <hr class="feed_hr">
            <div class="bottom_meta">
              <div class="row">
                <div class="bottom_left">
                  <div class="share_wrapper">
                    <div class="share"><a href="#" class="share_button"><i class="icon-heart"></i></a></div>
                    <div class="share_hidden">
                      <ul class="hover_heart">
                        <span class="internal_heart"><i class="icon-heart"></i> Share This Post</span>
                        <div class="social_links">
                          <li><span><i class="icon-twitter"></i> Twitter</span></li>
                          <li><span><i class="icon-facebook"></i> Facebook</span></li>
                          <li><span><i class="icon-pinterest"></i> Pinterest</span></li>
                        </div>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="bottom_right">
                  <a href="#">Corgi_like_bacon1</a> <span>|</span> <a href="#" class="show_comment_link">comment</a> <span>|</span> 2 days ago
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div> <!-- end span8 -->
    <div class="span4">
      <div class="corgi_feed_well">
        <div class="sidebar_header">
          <div class="sidebar_title">
            <h4>Explanatory Sidebar</h4>
          </div>
        </div>
        <hr class="feed_hr" />
        <div class="sidebar_interior">
          <i class="icon-ok"></i> Bacon is awesome!
          <br/><br/>
          <i class="icon-hand-right"></i> Rendered at <%=  Time.now.utc.strftime( "%H:%M:%S" ) %> UTC
          <br/><br/>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/feed_items/_fragment.html.erb
<% item ||= @item %>
<div class="feed_item">
    <div class="feed_body">
      <div class="row">
        <div class="feed_profile_pic">
          <%= image_tag item['profile_pic'], :class => "meta_image" %>
        </div>
        <div class="feed_text">
          <p><%= item['text'] %></p>
          <p>Rendered at <%=  Time.now.to_s %></p>
        </div>
      </div>
    </div>
    <div class="comment_area">
      <p>Add a comment</p>
      <form>
        <textarea rows="3" class="span6"></textarea><br/>
        <input type="submit" class="btn" />
      </form>
    </div>
    <hr class="feed_hr">
    <div class="bottom_meta">
      <div class="row">
        <div class="bottom_left">
          <div class="share_wrapper">
            <div class="share"><a href="#" class="share_button"><i class="icon-heart"></i></a></div>
            <div class="share_hidden">
              <ul class="hover_heart">
                <span class="internal_heart"><i class="icon-heart"></i> Share This Post</span>
                <div class="social_links">
                  <li><span><i class="icon-twitter"></i> Twitter</span></li>
                  <li><span><i class="icon-facebook"></i> Facebook</span></li>
                  <li><span><i class="icon-pinterest"></i> Pinterest</span></li>
                </div>
              </ul>
            </div>
          </div>
        </div>
        <div class="bottom_right">
          <a href="#"><%=  item['user_name'] %></a> <span>|</span> <a href="#" class="show_comment_link">comment</a> <span>|</span>
          <%= link_to time_ago_in_words( Time.at( item['created_at'].to_i ) ) + " ago", feed_feed_item_path( item['id'].to_s ) %>
        </div>
      </div>
    </div>
</div>

app/views/feed_items/show.html.erb
<div id="feed-body" class="container">
  <div class="row">
    <div class="span8">
      <div class="corgi_feed_well">
        <div class="feed_individual_item">
          <% if params[:id][0] == "X" %>
            <esi:include src="<%= url_for( format: 'esi' ) %>" onerror="continue" />
          <% else %>
            <%= render partial: "fragment" %>
          <% end %>
        </div>
      </div>
    </div> <!-- end span8 -->
    <div class="span4">
      <div class="corgi_feed_well">
        <div class="sidebar_header">
          <div class="sidebar_title">
            <h4>Explanatory Sidebar</h4>
          </div>
        </div>
        <hr class="feed_hr" />
        <div class="sidebar_interior">
          <i class="icon-ok"></i> Note same render time on item from listing page.
          <br/><br/>
          <i class="icon-ok"></i> This page <strong>is</strong> cached.
          <br/><br/>
          <i class="icon-hand-right"></i> Rendered at <%=  Time.now.utc.strftime( "%H:%M:%S" ) %> UTC
          <br/><br/>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/feeds/show.html.erb
<div id="feed-body" class="container">
  <div class="row">
    <div class="span8">
      <div class="corgi_feed_well">
        <% @items.each_with_index do |item, i| %>
            <div class="feed_stacked <%= 'last_feed_item' if i == @items.size - 1 %>">
              <% if item[0] == "{" %>
                <%= render partial: "feed_items/fragment", locals: { item: JSON.parse( item ) } %>
              <% else %>
                <esi:include src="<%= feed_feed_item_path( item, :format => :esi ) %>" onerror="continue" />
              <% end %>
            </div>
        <% end %>
      </div>
    </div> <!-- end span8 -->
    <div class="span4">
      <div class="corgi_feed_well">
        <div class="sidebar_header">
          <div class="sidebar_title">
            <h4>Explanatory Sidebar</h4>
          </div>
        </div>
        <hr class="feed_hr" />
        <div class="sidebar_interior">
          <i class="icon-ok"></i> Note different render times on feed items
          <br/><br/>
          <i class="icon-ok"></i> This page isn't cached.
          <br/><br/>
          <i class="icon-hand-right"></i> Rendered at <%=  Time.now.utc.strftime( "%H:%M:%S" ) %> UTC
          <br/><br/>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Varnishd Skillshare Test App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Varnishd Skillshare Class</a>
          <div class="nav-collapse collapse">
            <ul class="nav pull-right">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="#contact" id="login-button">Login</a></li>
              <li></li>
              <li></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <%= yield %>

    <br/><br/>
    <div class="corgi_footer">
      <div class="container">
        <div class="row">
          <div class="span12">
            <ul>
              <li><a href="">These</a></li>
              <li><a href="">Are</a></li>
              <li><a href="">Just</a></li>
              <li><a href="">Dummy</a></li>
              <li><a href="">Links</a></li>
            </ul>
            <div class="corgi_copyright">
              &copy; 2013 Bootstrap Micro
            </div>
          </div>
        </div>
      </div>
    </div>



</body>
</html>

app/views/private/contents/show.html.erb
<div id="feed-body" class="container">
  <div class="row">
    <div class="span8">
      <div class="corgi_feed_well">
        <div class="feed_stacked">
          <div class="feed_item">
            <div class="feed_body">
              <div class="row">
                <div class="feed_profile_pic">
                  <img src="<%= asset_path "corgi.jpg" %>" class="meta_image" />
                </div>
                <div class="feed_text">
                  This is very sensitive private content that no one can see if they don't
                  know the special username and password, but is also static so that it is cacheable.
                </div>
              </div>
            </div>
            <div class="comment_area">
              <p>Add a comment</p>
              <form>
                <textarea rows="3" class="span6"></textarea><br/>
                <input type="submit" class="btn" />
              </form>
            </div>
            <hr class="feed_hr" />
            <div class="bottom_meta">
              <div class="row">
                <div class="bottom_left">
                  <div class="share_wrapper">
                    <div class="share"><a href="#" class="share_button"><i class="icon-heart"></i></a></div>
                    <div class="share_hidden">
                    </div>
                  </div>
                </div>
                <div class="bottom_right">
                  <a href="#">Corgi_like_bacon1</a> <span>|</span> <a href="#" class="show_comment_link">comment</a> <span>|</span> 2 days ago
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div> <!-- end span8 -->
    <div class="span4">
      <div class="corgi_feed_well">
        <div class="sidebar_header">
          <div class="sidebar_title">
            <h4>Explanatory Sidebar</h4>
          </div>
        </div>
        <hr class="feed_hr" />
        <div class="sidebar_interior">
          <i class="icon-ok"></i> SSSSHHHHHH! Secrets
          <br/><br/>
          <i class="icon-hand-right"></i> Rendered at <%=  Time.now.utc.strftime( "%H:%M:%S" ) %> UTC
          <br/><br/>
        </div>
      </div>
    </div>
  </div>

</div>